`timescale 1ns/1ps

// tb_st7789_driver.v -- end-to-end check of the ST7789 LCD driver
// built by tools/build_st7789_flash_image.py: bootload the flash-
// handoff stub, let it redirect to the (SIMULATION-sized) flash
// image, and confirm the bit-banged SPI stream on GPIO_OUT actually
// reconstructs the exact init-sequence + fill-ring command/data bytes
// in order -- not just that some GPIO wiggling happens.
//
// Reconstructs the byte stream from GPIO_OUT[3:0] directly (bit-level,
// same way a real ST7789 panel would see it), rather than trusting
// mem.v's own write bus the way tb_flash_paging.v does -- this is
// specifically testing that the bit-banged SPI protocol ITSELF comes
// out correct, which is the whole point of this driver.
//
// Expected sequence generated by tools/ (see the inline Python snippet
// in the conversation/dev notes that produced test/st7789_expected_seq.hex)
// directly from the SAME constants build_st7789_flash_image.py uses,
// rather than hand-transcribed here -- avoids exactly the kind of
// transcription bug that's bitten this project's other testbenches.

module tb_st7789_driver;
    reg clk = 0;
    reg rst_n;
    reg [7:0] ui_in;
    wire [7:0] uo_out;
    wire [7:0] uio_out;
    wire [7:0] uio_oe;

    always #5 clk = ~clk;

    wire cs0  = uio_out[0]; // flash
    wire cs1  = uio_out[6]; // psram
    wire sck  = uio_out[3];
    wire mosi = uio_out[1];
    wire miso_flash, miso_psram;

    wire miso_bus = (!cs0) ? miso_flash : (!cs1) ? miso_psram : 1'b0;
    wire [7:0] uio_in = {5'b0, miso_bus, 2'b0};

    tt_um_pineapple_one dut (
        .ui_in   (ui_in),
        .uo_out  (uo_out),
        .uio_in  (uio_in),
        .uio_out (uio_out),
        .uio_oe  (uio_oe),
        .ena     (1'b1),
        .clk     (clk),
        .rst_n   (rst_n)
    );

    spi_ram_model u_flash (
        .cs_n (cs0),
        .sck  (sck),
        .mosi (mosi),
        .miso (miso_flash)
    );

    spi_ram_model u_psram (
        .cs_n (cs1),
        .sck  (sck),
        .mosi (mosi),
        .miso (miso_psram)
    );

    // Preload the flash model with the simulation-sized ST7789 image.
    reg [7:0] image [0:7259]; // st7789_flash_image.hex is 7260 bytes
    integer ci;
    initial begin
        $readmemh("st7789_flash_image.hex", image);
        for (ci = 0; ci < 7260; ci = ci + 1) u_flash.mem[ci] = image[ci];
    end

    task automatic reset_dut;
        begin
            ui_in = 0; rst_n = 0;
            repeat (10) @(posedge clk);
            rst_n = 1;
        end
    endtask

    task automatic send_bit(input b);
        begin
            ui_in[0] = b; ui_in[1] = 0;
            repeat (200) @(posedge clk);
            ui_in[1] = 1;
            repeat (200) @(posedge clk);
            ui_in[1] = 0;
            repeat (200) @(posedge clk);
        end
    endtask

    task automatic send_byte(input [7:0] b);
        integer bi;
        begin
            for (bi = 7; bi >= 0; bi = bi - 1) send_bit(b[bi]);
        end
    endtask

    reg [7:0] stub_bytes [0:3];
    localparam integer STUB_LEN = 4;

    // GPIO_OUT bit assignments per the driver's own header comment:
    // bit0=SCK bit1=MOSI bit2=DC bit3=CS.
    wire gpio_sck  = uo_out[0];
    wire gpio_mosi = uo_out[1];
    wire gpio_dc   = uo_out[2];
    wire gpio_cs   = uo_out[3];

    // Bit-bang capture: shift MOSI into a byte on every SCK rising
    // edge while CS is low, record (DC,byte) every 8 bits.
    reg [7:0] shift_reg;
    reg [2:0] bitcnt;
    reg       prev_sck;
    reg       capturing;

    localparam MAX_CAPTURE = 64;
    reg [8:0] captured [0:MAX_CAPTURE-1]; // {dc, byte}
    integer   cap_len;

    initial begin
        shift_reg = 0; bitcnt = 0; prev_sck = 0; capturing = 0; cap_len = 0;
    end

    always @(posedge clk) begin
        if (!rst_n) begin
            cap_len   <= 0;
            bitcnt    <= 0;
            prev_sck  <= 0;
        end else begin
            if (capturing && !gpio_cs && !prev_sck && gpio_sck) begin
                shift_reg <= {shift_reg[6:0], gpio_mosi};
                if (bitcnt == 3'd7) begin
                    bitcnt <= 0;
                    if (cap_len < MAX_CAPTURE) begin
                        captured[cap_len] <= {gpio_dc, shift_reg[6:0], gpio_mosi};
                        cap_len <= cap_len + 1;
                    end
                end else begin
                    bitcnt <= bitcnt + 3'd1;
                end
            end
            prev_sck <= gpio_sck;
        end
    end

    // Independently-generated expected sequence (see file header).
    reg [8:0] expected [0:23];
    integer EXPECTED_LEN;
    initial begin
        $readmemh("st7789_expected_seq.hex", expected);
        EXPECTED_LEN = 24;
    end

    integer k, errors;

    initial begin
        $dumpfile("tb_st7789_driver.vcd");
        $dumpvars(0, tb_st7789_driver);

        $readmemh("flash_handoff_stub.hex", stub_bytes);

        reset_dut();
        repeat (3000) @(posedge clk); // past self-test + a few demo-loop iterations

        ui_in[2] = 1; // START
        capturing = 1'b1;
        repeat (20) @(posedge clk);
        send_byte(STUB_LEN);
        for (ci = 0; ci < STUB_LEN; ci = ci + 1) send_byte(stub_bytes[ci]);

        // Give it time to run: init sequence (24 bytes) + 2 delay loops
        // (SIM_DELAY_COUNT=20 iterations each, a handful of on-chip
        // cycles per iteration) + one full fill-ring pass (3 pixels x
        // 2 bytes/pixel), each byte a full 8-bit x 3-cycle-per-bit
        // (per send_bit's own 200-cycle phases -- wait, this is the
        // CHIP's OWN bit-bang timing, driven by its own SW instructions
        // at 7 cycles/instruction each, not send_bit's host-side
        // timing) sequence. Budget generously.
        repeat (600000) @(posedge clk);

        errors = 0;
        if (cap_len < EXPECTED_LEN) begin
            errors = errors + 1;
            $display("FAIL: captured only %0d bytes, expected at least %0d", cap_len, EXPECTED_LEN);
        end else begin
            for (k = 0; k < EXPECTED_LEN; k = k + 1) begin
                if (captured[k] !== expected[k]) begin
                    errors = errors + 1;
                    $display("FAIL: byte %0d: captured dc=%b byte=0x%02x, expected dc=%b byte=0x%02x",
                              k, captured[k][8], captured[k][7:0], expected[k][8], expected[k][7:0]);
                end
            end
        end

        $display("Captured %0d bytes total (expected sequence is %0d bytes, image has 3 sim pixels so more may follow from ring repeats)", cap_len, EXPECTED_LEN);

        if (errors == 0)
            $display("PASS tb_st7789_driver: init sequence + first fill-ring pass match exactly");
        else
            $display("FAIL tb_st7789_driver: %0d mismatch(es)", errors);

        $finish;
    end

    initial begin
        #10000000;
        $display("TIMEOUT");
        $finish;
    end
endmodule
